version: "3"
services:
    web:
        build:
            # the soruce that is going to use
            # for the Dockerfile
            context: .
            # the docker file that is going to be used
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app 
    # responsible for testing
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app   
        command: ["npm", "run", "test"]